name: x86_64-linux-gnu
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Guix cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/guix
          key: guix-cache-${{ github.sha }}
          restore-keys: guix-cache-
      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1
        with:
          channels: |
            (list (channel
                   (name 'asahi)
                   (url "https://github.com/r0man/asahi-guix.git")
                   (branch "main")
                   (introduction
                    (make-channel-introduction
                     "d8f93a8a57be3e38f13916b4e5f3e1ad5ccee9de"
                     (openpgp-fingerprint
                      "D226 A339 D8DF 4481 5DDE  0CA0 3DDA 5252 7D2A C199"))))
                  (channel
                   (name 'guix)
                   (url "https://git.savannah.gnu.org/git/guix.git")
                   (branch "master")
                   (commit "c6480edbe3260a3bfb48361ca73e666b6d473f42")
                   (introduction
                    (make-channel-introduction
                     "9edb3f66fd807b096b48283debdcddccfea34bad"
                     (openpgp-fingerprint
                      "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA")))))
      - name: Ensure no locale warning
        run: test -z "$(guix --version 2>&1 >/dev/null)"
      - name: Build alsa-ucm-conf-asahi
        run: guix build -L . -v 5 alsa-ucm-conf-asahi
      - name: Build asahi-audio
        run: guix build -L . -v 5 asahi-audio
      - name: Build asahi-firmware
        run: guix build -L . -v 5 asahi-firmware
      - name: Build asahi-fwextract
        run: guix build -L . -v 5 asahi-fwextract
      # - name: Build asahi-scripts
      #   run: guix build -L . -v 5 asahi-scripts
      # - name: Build asahi-m1n1
      #   run: guix build -L . -v 5 asahi-m1n1
      - name: Build u-boot-apple-m1
        run: guix build -L . -v 5 u-boot-apple-m1
      - name: Build mesa-asahi-edge
        run: guix build -L . -v 5 mesa-asahi-edge
      - name: Build asahi-linux
        run: guix build -L . -v 5 asahi-linux
      - name: Build asahi-linux-edge
        run: guix build -L . -v 5 asahi-linux-edge
      # - name: Build installer
      #   run: guix system image -L . --image-type=efi-raw -v 5 asahi/guix/installer.scm
